spring:
  application:
    name: springboot-auth2.0-2
    
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: <>
            client-secret: <>
          google:
            client-id: <>
            client-secret: <>
            
server:
  port: 8081            
